name: eco_lalia
version: 1.0.0+1
description: A Flutter project for Ecolalia app

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.0
  flutter_tts: ^3.5.2
  speech_to_text: ^5.9.0
  path_provider: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
